import type { TableSchema } from "./types.js";

export const TARGET_SCHEMAS: TableSchema[] = [
  // ── tbCaseData ──
  {
    name: "tbCaseData",
    description: "Patient case information including demographics, ICD codes, and DRG data",
    columns: [
      { name: "coE2I222", type: "bigint", nullable: true, description: "Case ID" },
      { name: "coPatientId", type: "bigint", nullable: true, description: "Patient ID" },
      { name: "coE2I223", type: "datetime", nullable: true, description: "Admission date" },
      { name: "coE2I228", type: "datetime", nullable: true, description: "Discharge date" },
      { name: "coLastname", type: "nvarchar", nullable: true, description: "Patient last name" },
      { name: "coFirstname", type: "nvarchar", nullable: true, description: "Patient first name" },
      { name: "coGender", type: "nvarchar", nullable: true, description: "Patient gender" },
      { name: "coDateOfBirth", type: "datetime", nullable: true, description: "Date of birth" },
      { name: "coAgeYears", type: "bigint", nullable: true, description: "Age in years" },
      { name: "coTypeOfStay", type: "nvarchar", nullable: true, description: "Type of stay" },
      { name: "coIcd", type: "nvarchar", nullable: true, description: "ICD code" },
      { name: "coDrgName", type: "nvarchar", nullable: true, description: "DRG name" },
      { name: "coRecliningType", type: "nvarchar", nullable: true, description: "Reclining type" },
      { name: "coState", type: "nvarchar", nullable: true, description: "State" },
    ],
  },

  // ── tbImportAcData ──
  {
    name: "tbImportAcData",
    description: "epaAC care assessment data with ~265 coded assessment fields",
    columns: [
      { name: "coCaseId", type: "bigint", nullable: true, description: "Case ID" },
      { name: "coE0I001", type: "smallint", nullable: true, description: "Assessment type" },
      { name: "coE0I002", type: "smallint", nullable: true, description: "Type of care at home / before admission" },
      { name: "coE0I003", type: "smallint", nullable: true, description: "Non-native speaker" },
      { name: "coE0I004", type: "smallint", nullable: true, description: "Undesired weight loss" },
      { name: "coE0I005", type: "numeric", nullable: true, description: "BMI" },
      { name: "coE0I007", type: "smallint", nullable: true },
      { name: "coE0I008", type: "smallint", nullable: true, description: "Known diabetes mellitus" },
      { name: "coE0I009", type: "smallint", nullable: true, description: "Movement/mobility aids" },
      { name: "coE0I010", type: "smallint", nullable: true },
      { name: "coE0I011", type: "smallint", nullable: true, description: "Nutrition aids" },
      { name: "coE0I012", type: "smallint", nullable: true, description: "Hearing assistance" },
      { name: "coE0I013", type: "smallint", nullable: true, description: "Vision aids" },
      { name: "coE0I014", type: "smallint", nullable: true, description: "Weight" },
      { name: "coE0I015", type: "smallint", nullable: true, description: "Height" },
      { name: "coE0I021", type: "smallint", nullable: true, description: "Age" },
      { name: "coE0I043", type: "smallint", nullable: true, description: "Braden score - decubitus (pressure ulcer) risk" },
      { name: "coE0I070", type: "smallint", nullable: true },
      { name: "coE0I074", type: "smallint", nullable: true, description: "Food quantity prior to admission" },
      { name: "coE0I075", type: "smallint", nullable: true, description: "SPI" },
      { name: "coE0I076", type: "smallint", nullable: true, description: "Decubitus (pressure ulcer) risk (Braden)" },
      { name: "coE0I077", type: "smallint", nullable: true },
      { name: "coE0I078", type: "smallint", nullable: true },
      { name: "coE0I079", type: "smallint", nullable: true, description: "Need to evaluate for depression" },
      { name: "coE0I081", type: "smallint", nullable: true, description: "Pneumonia risk" },
      { name: "coE0I082", type: "smallint", nullable: true, description: "Malnutrition risk" },
      { name: "coE0I083", type: "smallint", nullable: true, description: "Risk of post-hospital care deficit" },
      { name: "coE0I0116", type: "smallint", nullable: true },
      { name: "coE0I0122", type: "smallint", nullable: true, description: "Nutrition in the coming week" },
      { name: "coE0I0134", type: "smallint", nullable: true },
      { name: "coE0I0141", type: "smallint", nullable: true, description: "Care level as per §15 SGB XI (long-term care insurance)" },
      { name: "coE0I0150", type: "smallint", nullable: true, description: "Need to evaluate for neurocognitive disorder" },
      { name: "coE0I0163", type: "smallint", nullable: true, description: "Prostheses/ Orthoses" },
      { name: "coE0I0168", type: "smallint", nullable: true, description: "Personal hygiene aids" },
      { name: "coE0I0173", type: "smallint", nullable: true, description: "Dressing aids" },
      { name: "coE0I0178", type: "smallint", nullable: true, description: "Toilet and incontinence aids (excl. diversion systems)" },
      { name: "coE0I0190", type: "smallint", nullable: true, description: "Speech/ communication aids" },
      { name: "coE0I0241", type: "smallint", nullable: true, description: "NRS value" },
      { name: "coE0I0262", type: "smallint", nullable: true },
      { name: "coE0I0266", type: "smallint", nullable: true, description: "Expert evaluation: further risk indicators for pressure sores" },
      { name: "coE0I0270", type: "smallint", nullable: true },
      { name: "coE0I0276", type: "smallint", nullable: true },
      { name: "coE0I0004", type: "nvarchar", nullable: true, description: "technical software company notes!" },
      { name: "coE0I0071", type: "smallint", nullable: true, description: "Non-native speaker, caregiver" },
      { name: "coE0I0077", type: "smallint", nullable: true },
      { name: "coE0I0081", type: "smallint", nullable: true, description: "Pneumonia risk" },
      { name: "coE2I001", type: "smallint", nullable: true, description: "Locomotion" },
      { name: "coE2I002", type: "smallint", nullable: true },
      { name: "coE2I003", type: "smallint", nullable: true, description: "Friction/shear force when changing position/transferring" },
      { name: "coE2I004", type: "smallint", nullable: true, description: "Altered gait" },
      { name: "coE2I005", type: "smallint", nullable: true, description: "Balance disturbances" },
      { name: "coE2I006", type: "smallint", nullable: true },
      { name: "coE2I007", type: "smallint", nullable: true },
      { name: "coE2I008", type: "smallint", nullable: true, description: "Exhaustion/fatigue" },
      { name: "coE2I009", type: "smallint", nullable: true, description: "Personal hygiene – Upper body" },
      { name: "coE2I010", type: "smallint", nullable: true, description: "Personal hygiene – Lower body" },
      { name: "coE2I011", type: "smallint", nullable: true, description: "Dressing/Undressing – Upper body" },
      { name: "coE2I012", type: "smallint", nullable: true, description: "Dressing/Undressing – Lower body" },
      { name: "coE2I013", type: "smallint", nullable: true, description: "Eating" },
      { name: "coE2I014", type: "smallint", nullable: true, description: "Quantity of nutrition (oral)" },
      { name: "coE2I015", type: "smallint", nullable: true, description: "Quantity of nutrition (total)" },
      { name: "coE2I017", type: "smallint", nullable: true, description: "Drinking" },
      { name: "coE2I018", type: "smallint", nullable: true },
      { name: "coE2I019", type: "smallint", nullable: true },
      { name: "coE2I020", type: "smallint", nullable: true },
      { name: "coE2I021", type: "smallint", nullable: true },
      { name: "coE2I022", type: "smallint", nullable: true, description: "swallowing disorders" },
      { name: "coE2I023", type: "smallint", nullable: true },
      { name: "coE2I024", type: "smallint", nullable: true, description: "Urinating" },
      { name: "coE2I025", type: "smallint", nullable: true, description: "Controlling urination" },
      { name: "coE2I026", type: "smallint", nullable: true, description: "Defecating" },
      { name: "coE2I027", type: "smallint", nullable: true, description: "Controlling defecation" },
      { name: "coE2I028", type: "smallint", nullable: true, description: "Excretion urgency/frequency" },
      { name: "coE2I029", type: "smallint", nullable: true, description: "Urinary diversion system" },
      { name: "coE2I030", type: "smallint", nullable: true, description: "Faecal diversion system" },
      { name: "coE2I031", type: "smallint", nullable: true, description: "Skin moisture" },
      { name: "coE2I032", type: "smallint", nullable: true, description: "Consciousness/ alertness" },
      { name: "coE2I033", type: "smallint", nullable: true, description: "Orientation (person, place, time, situation)" },
      { name: "coE2I034", type: "smallint", nullable: true },
      { name: "coE2I035", type: "smallint", nullable: true },
      { name: "coE2I036", type: "smallint", nullable: true },
      { name: "coE2I037", type: "smallint", nullable: true },
      { name: "coE2I038", type: "smallint", nullable: true },
      { name: "coE2I039", type: "smallint", nullable: true },
      { name: "coE2I040", type: "smallint", nullable: true },
      { name: "coE2I041", type: "smallint", nullable: true, description: "Falling/ staying asleep" },
      { name: "coE2I042", type: "smallint", nullable: true, description: "Sleep-wake cycle" },
      { name: "coE2I043", type: "smallint", nullable: true, description: "Breathing impaired (current)" },
      { name: "coE2I044", type: "smallint", nullable: true, description: "Chronic respiratory illness" },
      { name: "coE2I045", type: "smallint", nullable: true, description: "Ventilation > 24h curr. stay" },
      { name: "coE2I046", type: "smallint", nullable: true },
      { name: "coE2I047", type: "smallint", nullable: true },
      { name: "coE2I048", type: "smallint", nullable: true, description: "Sensory perception" },
      { name: "coE2I049", type: "smallint", nullable: true },
      { name: "coE2I050", type: "smallint", nullable: true, description: "Chronic pain" },
      { name: "coE2I051", type: "smallint", nullable: true },
      { name: "coE2I052", type: "smallint", nullable: true, description: "Wounds/path. skin changes" },
      { name: "coE2I053", type: "smallint", nullable: true, description: "Drugs that increase risk of falls/delirium" },
      { name: "coE2I054", type: "smallint", nullable: true, description: "Attentiveness" },
      { name: "coE2I055", type: "smallint", nullable: true, description: "Artificial feeding / prescribed additional food" },
      { name: "coE2I056", type: "smallint", nullable: true },
      { name: "coE2I057", type: "smallint", nullable: true, description: "Nausea" },
      { name: "coE2I058", type: "smallint", nullable: true, description: "Additional fluids" },
      { name: "coE2I059", type: "smallint", nullable: true, description: "Amount drunk" },
      { name: "coE2I060", type: "smallint", nullable: true, description: "Energy/Nutrient requirements" },
      { name: "coE2I061", type: "smallint", nullable: true, description: "Hearing" },
      { name: "coE2I062", type: "smallint", nullable: true, description: "Vision" },
      { name: "coE2I063", type: "smallint", nullable: true, description: "Expressing him-/herself" },
      { name: "coE2I064", type: "smallint", nullable: true, description: "Self-initiated activities" },
      { name: "coE2I065", type: "smallint", nullable: true, description: "Indicators of challenging behaviour" },
      { name: "coE2I066", type: "smallint", nullable: true, description: "Pain intensity" },
      { name: "coE2I067", type: "smallint", nullable: true, description: "Tube feeding" },
      { name: "coE2I068", type: "smallint", nullable: true, description: "Tracheostomy" },
      { name: "coE2I069", type: "smallint", nullable: true, description: "Everyday competence" },
      { name: "coE2I070", type: "smallint", nullable: true, description: "Sadness" },
      { name: "coE2I071", type: "smallint", nullable: true, description: "Anxiety" },
      { name: "coE2I072", type: "smallint", nullable: true },
      { name: "coE2I073", type: "smallint", nullable: true, description: "Mouth status" },
      { name: "coE2I074", type: "smallint", nullable: true },
      { name: "coE2I075", type: "smallint", nullable: true, description: "Ability to lead everyday life" },
      { name: "coE2I076", type: "smallint", nullable: true, description: "Ability to keep self occupied" },
      { name: "coE2I077", type: "smallint", nullable: true, description: "Housekeeping ability" },
      { name: "coE2I078", type: "smallint", nullable: true, description: "Ability to conduct external activities" },
      { name: "coE2I079", type: "smallint", nullable: true, description: "Memory retention" },
      { name: "coE2I080", type: "smallint", nullable: true, description: "Memory ability" },
      { name: "coE2I081", type: "smallint", nullable: true, description: "Ability to make decisions appropriate to the situation" },
      { name: "coE2I082", type: "smallint", nullable: true, description: "Processing/understanding information" },
      { name: "coE2I083", type: "smallint", nullable: true, description: "Ability to deal with changed living situations" },
      { name: "coE2I084", type: "smallint", nullable: true, description: "Ability to establish new relationships" },
      { name: "coE2I085", type: "smallint", nullable: true, description: "Maintaining existing relationships" },
      { name: "coE2I086", type: "smallint", nullable: true, description: "Meaning of life" },
      { name: "coE2I087", type: "smallint", nullable: true, description: "Foot status" },
      { name: "coE2I088", type: "smallint", nullable: true, description: "Long-term ventilation" },
      { name: "coE2I089", type: "nvarchar", nullable: true, description: "Free text - additional variable" },
      { name: "coE2I090", type: "nvarchar", nullable: true, description: "Free text, “Movement” category" },
      { name: "coE2I091", type: "nvarchar", nullable: true, description: "Free text, “Decubitus (pressure ulcer), wounds” category" },
      { name: "coE2I092", type: "nvarchar", nullable: true, description: "Free text, “Nutrition” category" },
      { name: "coE2I093", type: "nvarchar", nullable: true, description: "Free text, “Excretion” category" },
      { name: "coE2I095", type: "smallint", nullable: true, description: "Continence profile" },
      { name: "coE2I094", type: "nvarchar", nullable: true, description: "Free text, “Personal hygiene and dressing” category" },
      { name: "coE2I096", type: "nvarchar", nullable: true, description: "Free text, “Communication and information” category" },
      { name: "coE2I097", type: "nvarchar", nullable: true, description: "Free text, “Sleep” category" },
      { name: "coE2I098", type: "nvarchar", nullable: true, description: "Free text, “Regulation of bodily functions” category" },
      { name: "coE2I099", type: "nvarchar", nullable: true, description: "Free text, “Pain and emotional state” category" },
      { name: "coE2I100", type: "nvarchar", nullable: true, description: "Free text, risk analysis" },
      { name: "coE2I101", type: "nvarchar", nullable: true, description: "Free text, “Cognition, consciousness” category" },
      { name: "coE2I102", type: "smallint", nullable: true },
      { name: "coE2I103", type: "smallint", nullable: true },
      { name: "coE2I104", type: "smallint", nullable: true },
      { name: "coE2I105", type: "smallint", nullable: true },
      { name: "coE2I106", type: "smallint", nullable: true },
      { name: "coE2I107", type: "smallint", nullable: true },
      { name: "coE2I108", type: "smallint", nullable: true },
      { name: "coE2I109", type: "smallint", nullable: true },
      { name: "coE2I110", type: "smallint", nullable: true },
      { name: "coE2I111", type: "smallint", nullable: true },
      { name: "coE2I112", type: "smallint", nullable: true },
      { name: "coE2I113", type: "smallint", nullable: true },
      { name: "coE2I114", type: "smallint", nullable: true },
      { name: "coE2I115", type: "smallint", nullable: true },
      { name: "coE2I116", type: "smallint", nullable: true },
      { name: "coE2I117", type: "smallint", nullable: true },
      { name: "coE2I118", type: "smallint", nullable: true },
      { name: "coE2I119", type: "smallint", nullable: true },
      { name: "coE2I121", type: "smallint", nullable: true },
      { name: "coE2I122", type: "smallint", nullable: true },
      { name: "coE2I123", type: "smallint", nullable: true },
      { name: "coE2I124", type: "smallint", nullable: true },
      { name: "coE2I125", type: "smallint", nullable: true },
      { name: "coE2I126", type: "smallint", nullable: true },
      { name: "coE2I127", type: "smallint", nullable: true },
      { name: "coE2I128", type: "smallint", nullable: true },
      { name: "coE2I129", type: "smallint", nullable: true },
      { name: "coE2I130", type: "smallint", nullable: true },
      { name: "coE2I131", type: "smallint", nullable: true },
      { name: "coE2I132", type: "smallint", nullable: true },
      { name: "coE2I133", type: "smallint", nullable: true },
      { name: "coE2I134", type: "smallint", nullable: true },
      { name: "coE2I135", type: "smallint", nullable: true },
      { name: "coE2I136", type: "smallint", nullable: true, description: "Changes in stools" },
      { name: "coE2I137", type: "smallint", nullable: true },
      { name: "coE2I138", type: "smallint", nullable: true, description: "Homesickness" },
      { name: "coE2I139", type: "smallint", nullable: true },
      { name: "coE2I140", type: "smallint", nullable: true, description: "Able to cope with changed life situations (caregiver/ family)" },
      { name: "coE2I141", type: "smallint", nullable: true },
      { name: "coE2I142", type: "smallint", nullable: true },
      { name: "coE2I143", type: "smallint", nullable: true },
      { name: "coE2I144", type: "smallint", nullable: true },
      { name: "coE2I145", type: "smallint", nullable: true },
      { name: "coE2I146", type: "smallint", nullable: true },
      { name: "coE2I147", type: "smallint", nullable: true },
      { name: "coE2I148", type: "smallint", nullable: true },
      { name: "coE2I150", type: "smallint", nullable: true },
      { name: "coE2I151", type: "smallint", nullable: true },
      { name: "coE2I152", type: "smallint", nullable: true },
      { name: "coE2I154", type: "smallint", nullable: true },
      { name: "coE2I155", type: "smallint", nullable: true },
      { name: "coE2I156", type: "smallint", nullable: true },
      { name: "coE2I157", type: "smallint", nullable: true },
      { name: "coE2I158", type: "smallint", nullable: true },
      { name: "coE2I159", type: "smallint", nullable: true },
      { name: "coE2I160", type: "smallint", nullable: true },
      { name: "coE2I161", type: "smallint", nullable: true },
      { name: "coE2I162", type: "smallint", nullable: true },
      { name: "coE2I163", type: "smallint", nullable: true, description: "Fall history" },
      { name: "coE2I164", type: "smallint", nullable: true, description: "Current fall event" },
      { name: "coE2I165", type: "smallint", nullable: true, description: "Risk of falling" },
      { name: "coE2I166", type: "smallint", nullable: true, description: "Decubitus (pressure ulcer)" },
      { name: "coE2I167", type: "smallint", nullable: true, description: "Position change whilst lying down" },
      { name: "coE2I168", type: "smallint", nullable: true, description: "Maintaining sitting position" },
      { name: "coE2I169", type: "smallint", nullable: true, description: "Transfer" },
      { name: "coE2I170", type: "smallint", nullable: true, description: "Climbing stairs" },
      { name: "coE2I171", type: "smallint", nullable: true, description: "Care level requested (OPS 9-984.b)" },
      { name: "coE2I172", type: "smallint", nullable: true, description: "Ratio of fluid quantity to fluid requirements" },
      { name: "coE2I173", type: "smallint", nullable: true, description: "Factors influencing BMI" },
      { name: "coE2I178", type: "smallint", nullable: true, description: "Ability to keep oneself busy" },
      { name: "coE2I179", type: "smallint", nullable: true, description: "Sleep disorders" },
      { name: "coE2I217", type: "smallint", nullable: true, description: "Compensatory ability of the caregiver" },
      { name: "coE2I218", type: "smallint", nullable: true },
      { name: "coE2I220", type: "smallint", nullable: true, description: "Expert evaluation: further risk indicators for pressure sores" },
      { name: "coE2I221", type: "smallint", nullable: true },
      { name: "coE2I222", type: "bigint", nullable: true, description: "Case ID" },
      { name: "coE2I223", type: "datetime", nullable: true, description: "Admission datetime" },
      { name: "coE2I224", type: "smallint", nullable: true, description: "AdmTime" },
      { name: "coE2I225", type: "datetime", nullable: false, description: "Assessment datetime" },
      { name: "coE2I226", type: "bigint", nullable: true, description: "AssmtIDCase" },
      { name: "coE2I227", type: "smallint", nullable: true, description: "AssmtTime" },
      { name: "coE2I228", type: "datetime", nullable: true, description: "Discharge datetime" },
      { name: "coE2I229", type: "smallint", nullable: true, description: "Discharge time" },
      { name: "coE2I230", type: "nvarchar", nullable: true, description: "DeptDiv" },
      { name: "coE2I231", type: "nvarchar", nullable: true, description: "InstrVers" },
      { name: "coE2I232", type: "nvarchar", nullable: true, description: "WardName" },
      { name: "coE2I2000", type: "smallint", nullable: true, description: "Auxiliary aids for nutrition" },
      { name: "coE2I2013", type: "smallint", nullable: true, description: "Free text - “Caregiver” category" },
      { name: "coE2I2022", type: "smallint", nullable: true },
      { name: "coE2I2029", type: "smallint", nullable: true, description: "Pneumonia risk: further risk indicators (expert evaluation)" },
      { name: "coE2I2033", type: "smallint", nullable: true, description: "Expert evaluation: further risk indicators for pneumonia" },
      { name: "coE2I2092", type: "smallint", nullable: true, description: "Pains, acute" },
      { name: "coE2I2099", type: "smallint", nullable: true, description: "Pains, chronic" },
      { name: "coE2I2126", type: "smallint", nullable: true, description: "Oral health need for clarification" },
      { name: "coE2I2134", type: "smallint", nullable: true, description: "Ventilation aids" },
      { name: "coE2I2148", type: "smallint", nullable: true },
      { name: "coE2I2154", type: "smallint", nullable: true, description: "epaKOGNI" },
      { name: "coE2I2157", type: "smallint", nullable: true, description: "Exhaustion" },
      { name: "coE2I2165", type: "smallint", nullable: true },
      { name: "coE2I2170", type: "smallint", nullable: true, description: "Malnutrition risk (following MUST)" },
      { name: "coE2I2175", type: "smallint", nullable: true, description: "Malnutrition risk: point value" },
      { name: "coE2I2180", type: "smallint", nullable: true, description: "Delirium need for clarification" },
      { name: "coE2I2188", type: "smallint", nullable: true },
      { name: "coE2I2191", type: "smallint", nullable: true, description: "Fall risk need for clarification" },
      { name: "coE2I2195", type: "smallint", nullable: true, description: "Fear of falling" },
      { name: "coE2I2199", type: "smallint", nullable: true, description: "Fall history (12 months)" },
      { name: "coE2I2203", type: "smallint", nullable: true, description: "Impaired skin integrity, mild forms" },
      { name: "coE2I2207", type: "smallint", nullable: true, description: "Expert assessment: Further risk indicators of impaired skin integrity" },
      { name: "coE2I2211", type: "smallint", nullable: true, description: "Skin integrity need for clarification" },
      { name: "coE2I2216", type: "smallint", nullable: true, description: "CFI" },
      { name: "coE2I2222", type: "smallint", nullable: true, description: "Faecal continence profiles" },
      { name: "coE2I2256", type: "smallint", nullable: true },
      { name: "coE2I2267", type: "smallint", nullable: true, description: "Impaired skin integrity: Further risk indicators (expert assessment)" },
      { name: "coE2I2279", type: "smallint", nullable: true },
      { name: "coMaxDekuGrad", type: "smallint", nullable: true, description: "Maximum decubitus grade" },
      { name: "coDekubitusWertTotal", type: "smallint", nullable: true, description: "Total decubitus score" },
      { name: "coLastAssessment", type: "smallint", nullable: true, description: "Last assessment indicator" },
      { name: "coE3I0889", type: "nvarchar", nullable: true, description: "Case number" },
      { name: "coCaseIdAlpha", type: "nvarchar", nullable: true, description: "Alphanumeric case ID" },
    ],
  },

  // ── tbImportLabsData ──
  {
    name: "tbImportLabsData",
    description: "Laboratory test results including electrolytes, kidney function, blood counts, liver function, and coagulation markers",
    columns: [
      { name: "coCaseId", type: "bigint", nullable: true, description: "Case ID" },
      { name: "coSpecimen_datetime", type: "nvarchar", nullable: true, description: "Specimen collection datetime" },
      { name: "coSodium_mmol_L", type: "nvarchar", nullable: true, description: "Sodium value (mmol/L)" },
      { name: "coSodium_flag", type: "nvarchar", nullable: true, description: "Sodium abnormal flag" },
      { name: "cosodium_ref_low", type: "nvarchar", nullable: true, description: "Sodium reference low" },
      { name: "cosodium_ref_high", type: "nvarchar", nullable: true, description: "Sodium reference high" },
      { name: "coPotassium_mmol_L", type: "nvarchar", nullable: true, description: "Potassium value (mmol/L)" },
      { name: "coPotassium_flag", type: "nvarchar", nullable: true, description: "Potassium abnormal flag" },
      { name: "coPotassium_ref_low", type: "nvarchar", nullable: true, description: "Potassium reference low" },
      { name: "coPotassium_ref_high", type: "nvarchar", nullable: true, description: "Potassium reference high" },
      { name: "coCreatinine_mg_dL", type: "nvarchar", nullable: true, description: "Creatinine value (mg/dL)" },
      { name: "coCreatinine_flag", type: "nvarchar", nullable: true, description: "Creatinine abnormal flag" },
      { name: "coCreatinine_ref_low", type: "nvarchar", nullable: true, description: "Creatinine reference low" },
      { name: "coCreatinine_ref_high", type: "nvarchar", nullable: true, description: "Creatinine reference high" },
      { name: "coEgfr_mL_min_1_73m2", type: "nvarchar", nullable: true, description: "eGFR value (mL/min/1.73m2)" },
      { name: "coEgfr_flag", type: "nvarchar", nullable: true, description: "eGFR abnormal flag" },
      { name: "coEgfr_ref_low", type: "nvarchar", nullable: true, description: "eGFR reference low" },
      { name: "coEgfr_ref_high", type: "nvarchar", nullable: true, description: "eGFR reference high" },
      { name: "coGlucose_mg_dL", type: "nvarchar", nullable: true, description: "Glucose value (mg/dL)" },
      { name: "coGlucose_flag", type: "nvarchar", nullable: true, description: "Glucose abnormal flag" },
      { name: "coGlucose_ref_low", type: "nvarchar", nullable: true, description: "Glucose reference low" },
      { name: "coGlucose_ref_high", type: "nvarchar", nullable: true, description: "Glucose reference high" },
      { name: "coHemoglobin_g_dL", type: "nvarchar", nullable: true, description: "Hemoglobin value (g/dL)" },
      { name: "coHb_flag", type: "nvarchar", nullable: true, description: "Hemoglobin abnormal flag" },
      { name: "coHb_ref_low", type: "nvarchar", nullable: true, description: "Hemoglobin reference low" },
      { name: "coHb_ref_high", type: "nvarchar", nullable: true, description: "Hemoglobin reference high" },
      { name: "coWbc_10e9_L", type: "nvarchar", nullable: true, description: "White blood cell count (10e9/L)" },
      { name: "coWbc_flag", type: "nvarchar", nullable: true, description: "WBC abnormal flag" },
      { name: "coWbc_ref_low", type: "nvarchar", nullable: true, description: "WBC reference low" },
      { name: "coWbc_ref_high", type: "nvarchar", nullable: true, description: "WBC reference high" },
      { name: "coPlatelets_10e9_L", type: "nvarchar", nullable: true, description: "Platelet count (10e9/L)" },
      { name: "coPlatelets_flag", type: "nvarchar", nullable: true, description: "Platelets abnormal flag" },
      { name: "coPlt_ref_low", type: "nvarchar", nullable: true, description: "Platelets reference low" },
      { name: "coPlt_ref_high", type: "nvarchar", nullable: true, description: "Platelets reference high" },
      { name: "coCrp_mg_L", type: "nvarchar", nullable: true, description: "CRP value (mg/L)" },
      { name: "coCrp_flag", type: "nvarchar", nullable: true, description: "CRP abnormal flag" },
      { name: "coCrp_ref_low", type: "nvarchar", nullable: true, description: "CRP reference low" },
      { name: "coCrp_ref_high", type: "nvarchar", nullable: true, description: "CRP reference high" },
      { name: "coAlt_U_L", type: "nvarchar", nullable: true, description: "ALT value (U/L)" },
      { name: "coAlt_flag", type: "nvarchar", nullable: true, description: "ALT abnormal flag" },
      { name: "coAlt_ref_low", type: "nvarchar", nullable: true, description: "ALT reference low" },
      { name: "coAlt_ref_high", type: "nvarchar", nullable: true, description: "ALT reference high" },
      { name: "coAst_U_L", type: "nvarchar", nullable: true, description: "AST value (U/L)" },
      { name: "coAst_flag", type: "nvarchar", nullable: true, description: "AST abnormal flag" },
      { name: "coAst_ref_low", type: "nvarchar", nullable: true, description: "AST reference low" },
      { name: "coAst_ref_high", type: "nvarchar", nullable: true, description: "AST reference high" },
      { name: "coBilirubin_mg_dL", type: "nvarchar", nullable: true, description: "Bilirubin value (mg/dL)" },
      { name: "coBilirubin_flag", type: "nvarchar", nullable: true, description: "Bilirubin abnormal flag" },
      { name: "coBili_ref_low", type: "nvarchar", nullable: true, description: "Bilirubin reference low" },
      { name: "coBili_ref_high", type: "nvarchar", nullable: true, description: "Bilirubin reference high" },
      { name: "coAlbumin_g_dL", type: "nvarchar", nullable: true, description: "Albumin value (g/dL)" },
      { name: "coAlbumin_flag", type: "nvarchar", nullable: true, description: "Albumin abnormal flag" },
      { name: "coAlbumin_ref_low", type: "nvarchar", nullable: true, description: "Albumin reference low" },
      { name: "coAlbumin_ref_high", type: "nvarchar", nullable: true, description: "Albumin reference high" },
      { name: "coInr", type: "nvarchar", nullable: true, description: "INR value" },
      { name: "coInr_flag", type: "nvarchar", nullable: true, description: "INR abnormal flag" },
      { name: "coInr_ref_low", type: "nvarchar", nullable: true, description: "INR reference low" },
      { name: "coInr_ref_high", type: "nvarchar", nullable: true, description: "INR reference high" },
      { name: "coLactate_mmol_L", type: "nvarchar", nullable: true, description: "Lactate value (mmol/L)" },
      { name: "coLactate_flag", type: "nvarchar", nullable: true, description: "Lactate abnormal flag" },
      { name: "coLactate_ref_low", type: "nvarchar", nullable: true, description: "Lactate reference low" },
      { name: "coLactate_ref_high", type: "nvarchar", nullable: true, description: "Lactate reference high" },
    ],
  },

  // ── tbImportIcd10Data ──
  {
    name: "tbImportIcd10Data",
    description: "ICD-10 diagnosis codes and OPS procedure codes per case",
    columns: [
      { name: "coCaseId", type: "bigint", nullable: true, description: "Case ID" },
      { name: "coWard", type: "nvarchar", nullable: true, description: "Ward name" },
      { name: "coAdmission_date", type: "nvarchar", nullable: true, description: "Admission date" },
      { name: "coDischarge_date", type: "nvarchar", nullable: true, description: "Discharge date" },
      { name: "coLength_of_stay_days", type: "nvarchar", nullable: true, description: "Length of stay in days" },
      { name: "coPrimary_icd10_code", type: "nvarchar", nullable: true, description: "Primary ICD-10 code" },
      { name: "coPrimary_icd10_description_en", type: "nvarchar", nullable: true, description: "Primary ICD-10 description (English)" },
      { name: "coSecondary_icd10_codes", type: "nvarchar", nullable: true, description: "Secondary ICD-10 codes" },
      { name: "cpSecondary_icd10_descriptions_en", type: "nvarchar", nullable: true, description: "Secondary ICD-10 descriptions (English)" },
      { name: "coOps_codes", type: "nvarchar", nullable: true, description: "OPS procedure codes" },
      { name: "ops_descriptions_en", type: "nvarchar", nullable: true, description: "OPS procedure descriptions (English)" },
    ],
  },

  // ── tbImportDeviceMotionData ──
  {
    name: "tbImportDeviceMotionData",
    description: "Hourly aggregated motion and fall sensor data from wearable devices",
    columns: [
      { name: "coCaseId", type: "bigint", nullable: true, description: "Case ID" },
      { name: "coTimestamp", type: "datetime", nullable: true, description: "Measurement timestamp" },
      { name: "coPatient_id", type: "nvarchar", nullable: true, description: "Patient ID" },
      { name: "coMovement_index_0_100", type: "nvarchar", nullable: true, description: "Movement index (0-100)" },
      { name: "coMicro_movements_count", type: "nvarchar", nullable: true, description: "Micro movements count" },
      { name: "coBed_exit_detected_0_1", type: "nvarchar", nullable: true, description: "Bed exit detected (0/1)" },
      { name: "coFall_event_0_1", type: "nvarchar", nullable: true, description: "Fall event detected (0/1)" },
      { name: "coImpact_magnitude_g", type: "nvarchar", nullable: true, description: "Impact magnitude (g-force)" },
      { name: "coPost_fall_immobility_minutes", type: "nvarchar", nullable: true, description: "Post-fall immobility duration (minutes)" },
    ],
  },

  // ── tbImportDevice1HzMotionData ──
  {
    name: "tbImportDevice1HzMotionData",
    description: "Raw 1Hz IMU accelerometer and pressure zone sensor data",
    columns: [
      { name: "coCaseId", type: "bigint", nullable: true, description: "Case ID" },
      { name: "coTimestamp", type: "datetime", nullable: true, description: "Measurement timestamp" },
      { name: "coPatient_id", type: "nvarchar", nullable: true, description: "Patient ID" },
      { name: "coDevice_id", type: "nvarchar", nullable: true, description: "Device ID" },
      { name: "coBed_occupied_0_1", type: "nvarchar", nullable: true, description: "Bed occupied (0/1)" },
      { name: "coMovement_score_0_100", type: "nvarchar", nullable: true, description: "Movement score (0-100)" },
      { name: "coAccel_x_m_s2", type: "nvarchar", nullable: true, description: "Accelerometer X axis (m/s2)" },
      { name: "coAccel_y_m_s2", type: "nvarchar", nullable: true, description: "Accelerometer Y axis (m/s2)" },
      { name: "coAccel_z_m_s2", type: "nvarchar", nullable: true, description: "Accelerometer Z axis (m/s2)" },
      { name: "coAccel_magnitude_g", type: "nvarchar", nullable: true, description: "Accelerometer magnitude (g-force)" },
      { name: "coPressure_zone1_0_100", type: "nvarchar", nullable: true, description: "Pressure zone 1 (0-100)" },
      { name: "coPressure_zone2_0_100", type: "nvarchar", nullable: true, description: "Pressure zone 2 (0-100)" },
      { name: "coPressure_zone3_0_100", type: "nvarchar", nullable: true, description: "Pressure zone 3 (0-100)" },
      { name: "coPressure_zone4_0_100", type: "nvarchar", nullable: true, description: "Pressure zone 4 (0-100)" },
      { name: "coBed_exit_event_0_1", type: "nvarchar", nullable: true, description: "Bed exit event (0/1)" },
      { name: "coBed_return_event_0_1", type: "nvarchar", nullable: true, description: "Bed return event (0/1)" },
      { name: "coFall_event_0_1", type: "nvarchar", nullable: true, description: "Fall event detected (0/1)" },
      { name: "coImpact_magnitude_g", type: "nvarchar", nullable: true, description: "Impact magnitude (g-force)" },
      { name: "coEvent_id", type: "nvarchar", nullable: true, description: "Event ID" },
    ],
  },

  // ── tbImportMedicationInpatientData ──
  {
    name: "tbImportMedicationInpatientData",
    description: "Inpatient medication orders, changes, and administrations",
    columns: [
      { name: "coCaseId", type: "bigint", nullable: true, description: "Case ID" },
      { name: "coPatient_id", type: "nvarchar", nullable: true, description: "Patient ID" },
      { name: "coRecord_type", type: "nvarchar", nullable: true, description: "Record type (ORDER, CHANGE, ADMIN)" },
      { name: "coEncounter_id", type: "nvarchar", nullable: true, description: "Encounter ID" },
      { name: "coWard", type: "nvarchar", nullable: true, description: "Ward name" },
      { name: "coAdmission_datetime", type: "nvarchar", nullable: true, description: "Admission datetime" },
      { name: "coDischarge_datetime", type: "nvarchar", nullable: true, description: "Discharge datetime" },
      { name: "coOrder_id", type: "nvarchar", nullable: true, description: "Order ID" },
      { name: "coOrder_uuid", type: "nvarchar", nullable: true, description: "Order UUID" },
      { name: "coMedication_code_atc", type: "nvarchar", nullable: true, description: "ATC medication code" },
      { name: "coMedication_name", type: "nvarchar", nullable: true, description: "Medication name" },
      { name: "coRoute", type: "nvarchar", nullable: true, description: "Administration route" },
      { name: "coDose", type: "nvarchar", nullable: true, description: "Dose amount" },
      { name: "coDose_unit", type: "nvarchar", nullable: true, description: "Dose unit" },
      { name: "coFrequency", type: "nvarchar", nullable: true, description: "Administration frequency" },
      { name: "coOrder_start_datetime", type: "nvarchar", nullable: true, description: "Order start datetime" },
      { name: "coOrder_stop_datetime", type: "nvarchar", nullable: true, description: "Order stop datetime" },
      { name: "coIs_prn_0_1", type: "nvarchar", nullable: true, description: "PRN (as needed) flag (0/1)" },
      { name: "coIndication", type: "nvarchar", nullable: true, description: "Medication indication" },
      { name: "prescriber_role", type: "nvarchar", nullable: true, description: "Prescriber role" },
      { name: "order_status", type: "nvarchar", nullable: true, description: "Order status" },
      { name: "administration_datetime", type: "nvarchar", nullable: true, description: "Administration datetime" },
      { name: "administered_dose", type: "nvarchar", nullable: true, description: "Administered dose amount" },
      { name: "administered_unit", type: "nvarchar", nullable: true, description: "Administered dose unit" },
      { name: "administration_status", type: "nvarchar", nullable: true, description: "Administration status" },
      { name: "note", type: "nvarchar", nullable: true, description: "Additional notes" },
    ],
  },

  // ── tbImportNursingDailyReportsData ──
  {
    name: "tbImportNursingDailyReportsData",
    description: "Free-text nursing daily reports with shift information",
    columns: [
      { name: "coCaseId", type: "bigint", nullable: true, description: "Case ID" },
      { name: "coPatient_id", type: "nvarchar", nullable: true, description: "Patient ID" },
      { name: "coWard", type: "nvarchar", nullable: true, description: "Ward name" },
      { name: "coReport_date", type: "nvarchar", nullable: true, description: "Report date" },
      { name: "coShift", type: "nvarchar", nullable: true, description: "Shift (e.g. day, night)" },
      { name: "coNursing_note_free_text", type: "nvarchar", nullable: true, description: "Free-text nursing note" },
    ],
  },
];

/**
 * Look up a table schema by name (case-insensitive).
 */
export function getSchema(tableName: string): TableSchema | undefined {
  return TARGET_SCHEMAS.find(
    (s) => s.name.toLowerCase() === tableName.toLowerCase(),
  );
}

/**
 * Format one or all schemas into a human-readable string suitable for LLM context.
 * If tableName is provided, only that table is included; otherwise all tables.
 */
export function getSchemaPromptForLLM(tableName?: string): string {
  const schemas = tableName
    ? TARGET_SCHEMAS.filter(
        (s) => s.name.toLowerCase() === tableName.toLowerCase(),
      )
    : TARGET_SCHEMAS;

  if (schemas.length === 0) {
    return `No schema found for table "${tableName}".`;
  }

  return schemas
    .map((schema) => {
      const header = `## ${schema.name}\n${schema.description}\n`;
      const colLines = schema.columns.map((col) => {
        const nullable = col.nullable ? "NULL" : "NOT NULL";
        const desc = col.description ? ` -- ${col.description}` : "";
        return `  ${col.name} ${col.type} ${nullable}${desc}`;
      });
      return `${header}Columns (${schema.columns.length}):\n${colLines.join("\n")}`;
    })
    .join("\n\n");
}
